import { LegalLayout, LegalSection } from '@/components/LegalLayout';

export const metadata = { title: 'Privacy Policy — GigHuz' };

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="July 21, 2026">
      <LegalSection title="1. Overview">
        <p>
          This Privacy Policy explains what personal information GigHuz collects when
          you use the Platform, why we collect it, who we share it with, and the
          choices you have. It applies to Recruiters and Freelancers alike. Terms not
          defined here have the meaning given in our{' '}
          <a href="/terms" className="text-teal-700 hover:underline">Terms of Use</a>.
        </p>
      </LegalSection>

      <LegalSection title="2. Information We Collect">
        <p><strong>Account and authentication information.</strong> When you sign up, we (via Firebase Authentication) collect your email address, or your Google account's basic profile info if you sign in with Google, or your phone number if you sign in via SMS.</p>
        <p><strong>Profile information you provide.</strong> Depending on your role:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Freelancers:</strong> name, country, bio, skills, hourly rate and currency, portfolio links, WhatsApp number, profile picture, and — if you choose to add one — an uploaded resume file or an AI-generated resume built from your own profile data.</li>
          <li><strong>Freelancer payout details:</strong> bank account or mobile money information needed to route payouts through our payment providers.</li>
          <li><strong>Recruiters:</strong> name, company, and country.</li>
        </ul>
        <p><strong>Job and work content.</strong> Job descriptions, structured milestones, submitted deliverable files and notes, and audit feedback.</p>
        <p><strong>Payment information.</strong> Card details are collected and processed directly by Stripe — GigHuz does not store your full card number. Payout account details are shared with Paystack or Flutterwave to execute transfers.</p>
        <p><strong>Communications.</strong> If you provide a WhatsApp-capable phone number, we send you platform notifications (job matches, audit results, payment confirmations) via Twilio.</p>
        <p><strong>Usage information.</strong> Basic technical information generated by using the Platform, such as timestamps of actions you take (job posted, milestone funded, submission made).</p>
      </LegalSection>

      <LegalSection title="3. How We Use Your Information">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>To create and administer your account and verify your identity.</li>
          <li>To operate the marketplace: structuring jobs, matching Freelancers to jobs, auditing submissions, and processing escrow payments and payouts.</li>
          <li>To send you transactional notifications about your jobs, matches, submissions, and payments.</li>
          <li>To detect and prevent fraud, abuse, and violations of our Terms.</li>
          <li>To improve the Platform and its AI-assisted features.</li>
          <li>To comply with legal obligations, including those related to payment processing.</li>
        </ul>
        <p>We do not sell your personal information, and we do not use your profile or job data to serve third-party advertising.</p>
      </LegalSection>

      <LegalSection title="4. AI Processing of Your Data">
        <p>
          Certain data you provide is sent to our AI provider (currently Google
          Gemini) to power platform features:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Job descriptions are processed to generate structured milestones, skills, and budget estimates.</li>
          <li>Freelancer profile data (skills, ratings, availability, country) is processed to rank matches for a given job.</li>
          <li>Submission notes and file references are processed to generate an audit result and feedback.</li>
          <li>If you request an AI-generated resume, your existing profile fields (bio, skills, track record, portfolio links) are sent to generate resume text.</li>
          <li>Event data (e.g. "you were matched to a job") is used to generate the wording of notification messages.</li>
        </ul>
        <p>
          This processing is used to operate the specific feature you're using and is
          not used by GigHuz to build unrelated profiles about you. AI-generated
          outputs may be imperfect — see Section 4 of our Terms of Use.
        </p>
      </LegalSection>

      <LegalSection title="5. Who We Share Information With">
        <p><strong>Other Users, as needed for the Platform to work.</strong> A Freelancer's public profile information (name, country, skills, bio, rating, portfolio) is visible to Recruiters browsing talent or reviewing matches. A Recruiter's job postings are visible to matched Freelancers. Submitted deliverables are visible to the Recruiter on the relevant job.</p>
        <p><strong>Service providers who process data on our behalf</strong>, each only for the purpose described:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Google Firebase / Google Cloud</strong> — authentication, database (Firestore), and file storage (profile pictures, resumes).</li>
          <li><strong>Google Gemini</strong> — the AI processing described in Section 4.</li>
          <li><strong>Stripe</strong> — escrow payment collection from Recruiters.</li>
          <li><strong>Paystack / Flutterwave</strong> — payout delivery to Freelancers.</li>
          <li><strong>Twilio</strong> — WhatsApp notification delivery.</li>
        </ul>
        <p><strong>Legal and safety.</strong> We may disclose information if required by law, or where we believe in good faith it's necessary to protect the rights, safety, or property of GigHuz, our Users, or the public.</p>
        <p><strong>Business transfers.</strong> If GigHuz is involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction, subject to this Policy or its successor.</p>
      </LegalSection>

      <LegalSection title="6. Data Retention">
        <p>
          We retain account and transaction information for as long as your account is
          active and as needed to satisfy legal, tax, and accounting obligations
          related to payments made through the Platform. You may request deletion of
          your profile information as described in Section 8; note that records of
          completed financial transactions may be retained even after account deletion
          where required by law or by our payment processors.
        </p>
      </LegalSection>

      <LegalSection title="7. International Data Transfers">
        <p>
          GigHuz and its service providers operate infrastructure in multiple
          countries. By using the Platform, you understand that your information may
          be transferred to, stored, and processed in a country other than the one you
          reside in, which may have different data protection laws.
        </p>
      </LegalSection>

      <LegalSection title="8. Your Rights and Choices">
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Access and correction.</strong> You can view and update most of your profile information directly from your account.</li>
          <li><strong>Deletion.</strong> You can request that we delete your account and associated profile data, subject to the retention needs described in Section 6.</li>
          <li><strong>Portability.</strong> You can request a copy of the profile information you provided to us.</li>
          <li><strong>Communication preferences.</strong> You can update or remove your WhatsApp number from your profile to stop receiving WhatsApp notifications.</li>
        </ul>
        <p>
          Depending on where you live, you may have additional rights under laws such
          as the GDPR or similar regional data-protection frameworks. To exercise any
          of these rights, contact us using the details in Section 10.
        </p>
      </LegalSection>

      <LegalSection title="9. Children's Privacy">
        <p>
          GigHuz is not directed to, and is not intended for use by, anyone under 18.
          We do not knowingly collect personal information from children. If you
          believe a child has provided us with personal information, contact us and
          we'll take steps to delete it.
        </p>
      </LegalSection>

      <LegalSection title="10. Changes to This Policy and Contact">
        <p>
          We may update this Privacy Policy from time to time; material changes will
          be reflected by an updated "Last updated" date above. Questions about this
          Policy, or requests relating to your data, can be sent to{' '}
          <a href="mailto:privacy@gighuz.com" className="text-teal-700 hover:underline">privacy@gighuz.com</a>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
